# Source for csv inputs; most files will change infrequently, although the
# ones prefaced with 'current' will change weekly

inputs:
    key_file: settings/key_file.csv
    current_applications: current_applications.csv
    current_roster: current_students.csv
    strategies: settings/strategy_definitions.csv
    targets: settings/targets_by_strategy.csv
    colleges: settings/all_colleges.csv
    acttosat: settings/act_to_sat.csv
    bump_list: settings/bump_list.csv
    ambitious_pp: settings/app_programs.csv

campus_list:
    - Baker
    - Bulls
    - Butler
    - Comer
    - DRW
    - Golder
    - Hansberry
    - Johnson
    - Mansueto
    - Muchin
    - Noble
    - Pritzker
    - Rauner
    - RoweClark
    - Speer
    - TNA
    - UIC

###################################################################
# Output details:
output_folder: Reports

###################################################################
# Location to save live pulls from the Google Docs
#
live_backup_folder: live_backups
live_archive_folder: live_backups/archives
live_backup_prefix: noble-network

###################################################################
# Settings for reading and processing "current" inputs
#
roster_fields: # fields to grab from the roster file in order
    - Campus
    - EFC
    - LastFirst
    - StudentID # will be the index
    - GPA
    - ACT
    - InterimSAT
    - SAT
    - 'Race/ Eth'
    - Counselor
    - Advisor
    - Cohort
    - Gender
      
app_fields: # fields to grab from the Naviance application data in order
    - Campus
    - hs_student_id
    - last_name
    - first_name
    - middle_name
    - collegename
    - stage
    - type
    - result_code
    - attending
    - waitlisted
    - deferred
    - comments
    - NCES

use_complex: # Schools that want a more complex set of award fields
    - Alpha
    - Bulls
    - Comer
    - Butler

award_sort:
    Standard:
        - Student
        - College/University
    Complex:
        - Student
        - 6-Year Minority Grad Rate
        - College/University

app_status_to_include: #Statuses to push to the Google Doc
    Standard:
        - Accepted!
        - CHOICE!
        - Pending
        - Submitted
        - Waitlist
        - Deferred
    Comer:
        - Accepted!
        - CHOICE!
        - Pending
        - Submitted
        - Waitlist
        - Deferred
        - Denied

###################################################################
# Details about the planned columns in the main tabs
#
award_fields:
    Standard:
        - Student
        - College/University
        - Result (from Naviance)
        - SID
        - NCESid
        - Home/Away
        - Tuition & Fees (including insurance if req.)
        - Room & board (if not living at home)
        - College grants & scholarships
        - Government grants (Pell/SEOG/MAP)
        - Net Price (before Loans) <CALCULATED>
        - Student Loans offered (include all non-parent)
        - Out of Pocket Cost (Direct Cost-Grants-Loans) <CALCULATED>
        - Your EFC <DRAWN FROM OTHER TAB>
        - Unmet need <CALCULATED>
        - Work Study (enter for comparison if desired)
        - Unique
        - Award
    Complex:
        - Student
        - Target Grad Rate
        - Ideal Grad Rate
        - College/University
        - "Selectivity\n1=Most+\n2=Most\n3=Highly\n4=Very\n5=Competitive\n6=Less\n7=Non\n8=2 year"
        - Result (from Naviance)
        - 6-Year Minority Grad Rate
        - SID
        - NCESid
        - Home/Away
        - Award Receiv- ed?
        - Tuition & Fees (including insurance if req.)
        - Room & board (if not living at home)
        - College grants & scholarships
        - Government grants (Pell/SEOG/MAP)
        - Net Price (before Loans) <CALCULATED>
        - Student Loans offered (include all non-parent)
        - Out of Pocket Cost (Direct Cost-Grants-Loans) <CALCULATED>
        - Your EFC <DRAWN FROM OTHER TAB>
        - Unmet need <CALCULATED>
        - Work Study (enter for comparison if desired)
        - Unique
        - Award
 
efc_tab_fields: #assumes the first is the label for the index
    - StudentID
    - LastFirst
    - EFC
    - Non-award letter scholarships ($)
    - "# of years for non-award letter scholarship (1, 2, 3, or 4)"
    - Scholarship details (name & other details if not a one time or standard recurring award
    - Acceptances
    - Unique Awards
    - '% of awards collected'
    - Total grants & scholarships (1 yr value)
    - Total grants & scholarships (4 yr value)

###################################################################
# Details about the columns in the merged file
#
live_award_fields:
    - SID
    - NCESid
    - Home/Away
    - Campus
    - Student
    - College/University
    - Result (from Naviance)
    - Tuition & Fees (including insurance if req.)
    - Room & board (if not living at home)
    - College grants & scholarships
    - Government grants (Pell/SEOG/MAP)
    - Student Loans offered (include all non-parent)
    - Work Study (enter for comparison if desired)
    - Unique
    - Award

live_efc_fields:
    - Campus
    - LastFirst
    - EFC
    - Non-award letter scholarships ($)
    - '# of years for non-award letter scholarship (1, 2, 3, or 4)'
    - 'Scholarship details (name & other details if not a one time or standard recurring award'
    - Acceptances
    - Unique Awards
    - '% of awards collected'
    - Total grants & scholarships (1 yr value)
    - Total grants & scholarships (4 yr value)
      

live_decision_fields: #StudentID is the index
    - Campus
    - LastFirst
    - startRow
    - endRow
    - College Choice (dropdown should match with student options)
    - match (hidden column)
    - Ambitious Postsecondary Pathway choice (if selected to left)
    - Other College Choice (leave column to the left blank if entering here)
    - PGR for choice school
    - Student TGR
    - PGR-TGR
    - PGR within 10% of TGR?
    - Reason for not meeting TGR
    - Out of Pocket at Choice (pulls from Award data tab weekly)
    - EFC (pulls from EFC tab)
    - Exceeds Goal? (no more than 3000 over EFC)
    - Comments (use for undermatching and affordability concerns)

###################################################################
# Details about the columns in the decisions options sheet
#

# Code will depend on the order of these, but putting it here allows
# for tweaks to the exact label wording above
decision_option_fields:
    - SID
    - NCESid
    - Home/Away
    - College/University
    - Result (from Naviance)
    - Out of Pocket Cost (Direct Cost-Grants-Loans) <CALCULATED>
    - Student Loans offered (include all non-parent)
    - College grants & scholarships

###################################################################
# Details about the drive setup
#
drive_folder: 1cjrHd7PRgPt0R8aznGpgqAU25XYPxej2 #2022
#drive_folder: 1ty-Qwnyo4s16eIHkkM_tLwIRmSSZaFch #2021 [REAL]
#drive_folder: 170xfyi8I00giWO3XMSJRBUMXN3Wwn1H2 #2021 [TEST]
#drive_folder: 1dbDCbC6lLHR7Ez9H3-9knBuL9k0JnJ4K 2020
#drive_folder: 19bQt8AJI6mYiUAycIOYhGmegGwPCpkM_ 2019
#drive_folder: 1NGcIt5fvcwjNdAa-JTop8qwXG1vEz4ha 2018
file_stem: 2022 Aid Award Tracker

###################################################################
# Details about the Google doc structure:
#
efc_tab_name:
    Standard: EFC data
    #Comer: 7.1.EFC data
    #Butler: Student data and summaries
    #UIC: EFC and Scholarship data
award_tab_name:
    Standard: Award data
    #Comer: 7.Award Data
decision_options_tab_name:
    Standard: DecisionOptions
decision_tab_name:
    Standard: Decisions
    #Comer: 7.2.Decisions
efc_header_row:
    Standard: 1
award_header_row:
    Standard: 1
decision_options_header_row:
    Standard: 1
decision_header_row:
    Standard: 1
decision_defaults: #keys are the options and values are "grad rate" for choice
    Standard:
        'Ambitious Postsecondary Pathway (select to right)': 0.17
        'IEP: Occupational CPS HS': 'N/A'
        'IEP: 5th year at Noble campus': 'N/A'
        'No college/working': 0.0

###################################################################
# Details about the Excel report
#
report_folder: output_reports
report_filename: CAMPUS_Decision_Reports_DATE.xlsx
report_award_fields: #Columns in 'Award data' tab (generally from live_award)
    # fields with x in the front go to the df, but not the excel
    - SID: SID
    - NCESid: NCESid
    - Home/Away: Home/Away
    - Race/Eth: ROSTER:SID:Race/ Eth
    - Campus: ROSTER:SID:Campus
    - Last,First: Student
    - College/University: College/University
    - Result: Result (from Naviance)
    - 'xGrad rate_All': COLLEGE:NCESid:Adj6yrGrad_All  # just for calculating
    - 'xGrad rate_AAH': COLLEGE:NCESid:Adj6yrGrad_AA_Hisp
    - 'Grad rate': SPECIAL:xGrad rate_All:xGrad rate_AAH
    - 'Grad rate for sorting': SPECIAL:Grad rate:comments
    - 'Tuition & Fees': Tuition & Fees (including insurance if req.)
    - 'Room & board': Room & board (if not living at home)
    - 'College grants & scholarships': College grants & scholarships
    - 'Government grants': Government grants (Pell/SEOG/MAP)
    - 'Student Loans offered': Student Loans offered (include all non-parent)
    - 'Work Study': Work Study (enter for comparison if desired)
    - comments: APPS:NCESid:SID:comments
    - Unique: SPECIAL:0:1
    - Award: SPECIAL:0:1
    - MoneyCode: COLLEGE:NCESid:MoneyCode
report_award_sorts:
    Standard:  # Another section should be added for campus-specific sort instructions
        - Campus: True
        - Last,First: True
        - 'Grad rate for sorting': False
        - Home/Away: True

report_student_fields: #Columns in 'Students' tab (generally from live_efc)
    # fields with x in the front go to the df, but not the excel
    # ROSTER fields are from live_efc, DECISION from live_decision
    # COMMENT OUT THE DECISION FIELDS IF THE DECISION TAB DOESN'T EXIST
    - Campus: Campus
    - StudentID: INDEX:0
    - LastFirst: LastFirst
    - EFC: EFC
    - TGR: ROSTER:Target Grad Rate
    - GPA: ROSTER:GPA
    - SAT: ROSTER:local_sat_max
    - Counselor: ROSTER:Counselor
    - Advisor: ROSTER:Advisor
    - Strategy: ROSTER:Stra-tegy
    - 'Race / Ethnicity': ROSTER:Race/ Eth
    - Cohort: ROSTER:Cohort
    - 'College Choice': DECISION:College Choice (dropdown should match with student options)
    - 'Ambitious Postsecondary Pathway choice': DECISION:Ambitious Postsecondary Pathway choice (if selected to left)
    - 'Other College Choice': DECISION:Other College Choice (leave column to the left blank if entering here)
    - 'PGR for choice school': DECISION:PGR for choice school
    - 'PGR-TGR': DECISION:PGR-TGR
    - 'PGR within 10% of TGR?': DECISION:PGR within 10% of TGR?
    - 'Reason for not meeting TGR': DECISION:Reason for not meeting TGR
    - 'Out of Pocket at Choice (pulls from Award data tab weekly)': DECISION:Out of Pocket at Choice (pulls from Award data tab weekly)
    - 'EFC (pulls from EFC tab)': DECISION:EFC (pulls from EFC tab)
    - 'Exceeds Goal? (no more than 3000 over EFC)': DECISION:Exceeds Goal? (no more than 3000 over EFC)
    #- 'Flag for AC (use for notes to help AC with summer counseling)': DECISION:Flag for AC (use for notes to help AC with summer counseling)
    - 'Comments (use for undermatching and affordability concerns)': DECISION:Comments (use for undermatching and affordability concerns)

summary_settings:
    columns:
        - Strategy: p_header
        - '# Students': p_header
        - 'Target Grad Rate (TGR)': p_header_y
        - 'Total 4 year value of scholarships awarded': p_header_o
        - 'Average 4 year value of scholarships per student': p_header_o
        - '% of students with decisions': p_header_y
        - '% of awards collected': p_header_y
        - PGR: p_header
        - 'PGR-TGR': p_header
        - '% of students w/in 10% of TGR': p_header
        - '% of students w/ award at choice': p_header_o
        - 'Avg. unmet need at choice college': p_header_o
    strats:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - TBD
        - N/A
    campuses:
        - Baker
        - Bulls
        - Butler
        - Comer
        - DRW
        - Golder
        - Hansberry
        - Johnson
        - Mansueto
        - Muchin
        - Noble
        - Pritzker
        - Rauner
        - RoweClark
        - Speer
        - TNA
        - UIC


report_student_sorts:
    Standard:
      - Campus: True
      - LastFirst: True
    Hansberry:
      - Campus: True
      - Counselor: True
      - LastFirst: True
    Mansueto:
      - Campus: True
      - Counselor: True
      - LastFirst: True
    UIC:
      - Campus: True
      - Counselor: True
      - Cohort: True
      - LastFirst: True
    Rauner:
      - Campus: True
      - Cohort: True
      - LastFirst: True
    Bulls:
      - Campus: True
      - Counselor: True
      - LastFirst: True


report_award_formats: #Option formats to override defaults for each column
    SID:
        width: 59

# ---------------------------------------------------------------
# Formatting for Excel
excel_formats:
    # copy of Pandas default header
    p_header:
        bold: True
        align: center
        valign: top
        text_wrap: True
        left: 1
        bottom: 1
        right: 1
        top: 1
    # copy of Pandas default header, yellow
    p_header_y:
        bg_color: yellow
        bold: True
        align: center
        valign: top
        text_wrap: True
        left: 1
        bottom: 1
        right: 1
        top: 1
    # copy of Pandas default header, orange
    p_header_o:
        bg_color: orange
        bold: True
        align: center
        valign: top
        text_wrap: True
        left: 1
        bottom: 1
        right: 1
        top: 1
    #non-colored number formats
    dollar_fmt:
        num_format: '_($* #,##0.00_);_($* (#,##0.00);_($* "-"??_);_(@_)'
    dollar_no_cents_fmt:
        num_format: '_($* #,##00_);_($* (#,##0);_($* "-"??_);_(@_)'
    percent_fmt:
        num_format: 0.0%
    percent_centered:
        num_format: 0.0%
        align: center
    single_percent_centered:
        num_format: 0%
        align: center
    single_percent_centered_dash_bottom:
        num_format: 0%
        align: center
        bottom: 3
    single_percent_centered_solid_bottom:
        num_format: 0%
        align: center
        bottom: 1
    centered_integer:
        num_format: '#0'
        align: center
    sum_dollar:
        num_format: '_($* #,##00_);_($* (#,##0);_($* "-"??_);_(@_)'
        bold: True
        bottom: 6
        top: 2
    sum_percent:
        num_format: 0%
        align: center
        bold: True
        bottom: 6
        top: 2
    sum_centered_integer:
        num_format: '#0'
        align: center
        bold: True
        bottom: 6
        top: 2

    # non-colored non-number formats
    centered:
        num_format: '#0'
        align: center
    centered_right:
        num_format: '#0'
        align: center
        right: 1
    right:
        num_format: '#0'
        right: 1
    bold:
        num_format: '#0'
        bold: True
        align: left
    bold_wrap:
        num_format: '#0'
        bold: True
        align: left
        text_wrap: True
        bottom: 1
    bold_center_wrap:
        num_format: '#0'
        bold: True
        align: center
        valign: top
        text_wrap: True
        bottom: 1
    bold_center_wrap_right:
        num_format: '#0'
        bold: True
        align: center
        valign: top
        text_wrap: True
        bottom: 1
        right: 1
    left_normal_text:
        bold: False
        align: left
        top: 0
        left: 0
        right: 0
        bottom: 0
    dash_bottom:
        bottom: 3
    solid_bottom:
        bottom: 1
    solid_bottom_right:
        bottom: 1
        right: 1
    dash_bottom_right:
        bottom: 3
        right: 1
    bold_underline:
        bold: True
        align: left
        underline: True
        